CREATE USER IF NOT EXISTS '${OAS_DB_USER}'@'%' IDENTIFIED BY '${OAS_DB_PASSWORD}';
GRANT CREATE, ALTER, DROP, SELECT, INSERT, UPDATE, DELETE, INDEX, CREATE TEMPORARY TABLES ON *.* TO '${OAS_DB_USER}'@'%';

CREATE DATABASE IF NOT EXISTS ${GRAFANA_DB};
CREATE USER IF NOT EXISTS '${GRAFANA_DB_USER}'@'%' IDENTIFIED BY '${GRAFANA_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${GRAFANA_DB}.* TO '${GRAFANA_DB_USER}'@'%';

FLUSH PRIVILEGES;
