CREATE USER IF NOT EXISTS '${OAS_DB_USER}'@'%' IDENTIFIED BY '${OAS_DB_PASSWORD}';
GRANT CREATE, ALTER, DROP, SELECT, INSERT, UPDATE, DELETE, INDEX, CREATE TEMPORARY TABLES, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO '${OAS_DB_USER}'@'%';

CREATE USER IF NOT EXISTS '${GRAFANA_DB_USER}'@'%' IDENTIFIED BY '${GRAFANA_DB_PASSWORD}';
GRANT SELECT ON *.* TO '${GRAFANA_DB_USER}'@'%';

FLUSH PRIVILEGES;
